version: '3.9'
services:
  axon:
    container_name: axon
    image: axoniq/axonserver:latest-jdk-17-dev
    ports:
      - 8024:8024
      - 8124:8124
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx4096m"
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
  stockfish:
    container_name: stockfish
    build:
      context: stockfish
      dockerfile: Dockerfile
    image: latest-stockfish
    ports:
      - 23249:23249
  gui:
    container_name: gui
    build:
      context: gui
      dockerfile: Dockerfile
    image: gui
    ports:
      - 3000:3000
