version: '3.8'
services:
  axon:
    container_name: axon
    image: axoniq/axonserver:latest-jdk-17-dev
    ports:
      - 8024:8024
      - 8124:8124
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
  stockfish:
    container_name: stockfish
    build:
      context: stockfish
      dockerfile: Dockerfile
    image: latest-stockfish
    platform: linux/arm64
    ports:
      - 23249:23249
  gui:
    container_name: gui
    build:
      context: gui
      dockerfile: Dockerfile
    image: gui
    platform: linux/arm64
    ports:
      - 3000:3000
