### Create game

POST http://localhost:8080/games
Content-Type: application/json
User: {{player1}}

{
  "invitePlayerId": "{{player1}}",
  "minutes": 5,
  "incrementSeconds": 3,
  "pieceColor": "WHITE"
}

> {%
    client.global.set("game_id", response.body.gameId);
%}

### Accept invitation

POST http://localhost:8080/games/{{game_id}}/accept-invite
Content-Type: application/json
User: {{player2}}

### Play 1 move

POST http://localhost:8080/games/{{game_id}}/play
Content-Type: application/json
User: {{player1}}

{ "move": "f3" }

### Black draw

POST http://localhost:8080/games/{{game_id}}/draw
Content-Type: application/json
User: {{player2}}

### White accepts draw

POST http://localhost:8080/games/{{game_id}}/draw
Content-Type: application/json
User: {{player1}}
