### Create game

POST http://localhost:8080/games
Content-Type: application/json
User: {{player1}}

{
  "invitePlayerId": "{{player2}}",
  "minutes": 5,
  "incrementSeconds": 0,
  "pieceColor": "WHITE"
}

> {%
    client.global.set("game_id", response.body.gameId);
%}

### Accept invitation

POST http://localhost:8080/games/{{game_id}}/accept-invite
Content-Type: application/json
User: {{player2}}
