### Create player 1

POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "white-knight",
  "bot": true,
  "level": 5
}

> {%
    client.global.set("player1", response.body.playerId);
%}

### Create bot player

POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "black-knight",
  "bot": true,
  "level": 20
}

> {%
    client.global.set("player2", response.body.playerId);
%}
