### Quick pair

POST http://localhost:8080/requests/quick-pair
Content-Type: application/json
User: {{player2}}

{
  "minutes": 5,
  "incrementSeconds": 3
}

### Create game

POST http://localhost:8080/games
Content-Type: application/json
User: {{player1}}

{
  "minutes": 5,
  "incrementSeconds": 3,
  "pieceColor": "WHITE"
}

> {%
    client.global.set("game_id", response.body.gameId);
%}


### Get game

GET http://localhost:8080/games/{{game_id}}
