### Play 1 move

POST http://localhost:8080/games/{{game_id}}/play
Content-Type: application/json
User: {{player1}}

{ "move": "f3" }

### Play 2 move

POST http://localhost:8080/games/{{game_id}}/play
Content-Type: application/json
User: {{player2}}

{ "move": "e6" }

### Play 3 move

POST http://localhost:8080/games/{{game_id}}/play
Content-Type: application/json
User: {{player1}}

{ "move": "g4" }

### Play 4 move

POST http://localhost:8080/games/{{game_id}}/play
Content-Type: application/json
User: {{player2}}

{ "move": "Qh4" }
