management.endpoints.web.exposure.include: "*"

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: board
          predicates:
            - Path=/boards/**
          uri: http://localhost:8083
        - id: game
          predicates:
            - Path=/games/**, /requests/**
          uri: http://localhost:8084
        - id: player
          predicates:
            - Path=/players/**
          uri: http://localhost:8081
        - id: frontend
          predicates:
            - Path=/**
          uri: http://localhost:3000
