management.endpoints.web.exposure.include: "*"

spring:
  application:
    name: Engine Service
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

axon:
  serializer:
    general: default
    events: jackson
    messages: jackson

uci:
  host: localhost
  port: 23249

server:
  port: 8082
