management.endpoints.web.exposure.include: "*"

spring:
  application:
    name: Board Service
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

axon:
  serializer:
    general: default
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      BoardsEventHandler:
        mode: pooled
        thread-count: 4
        initial-segment-count: 8
server:
  port: 8083
